// Final preview trigger after login-scope fix
const fs=require('fs')
const assert=require('node:assert/strict')

const migration=fs.readFileSync('supabase/migrations/20261005143000_activity_log.sql','utf8')
const tracker=fs.readFileSync('components/ActivityTracker.tsx','utf8')
const helper=fs.readFileSync('lib/activityLog.ts','utf8')
const shell=fs.readFileSync('components/AppShell.tsx','utf8')
const login=fs.readFileSync('app/login/page.tsx','utf8')
const users=fs.readFileSync('app/users/page.tsx','utf8')

assert.match(migration,/alter table public\.activity_logs enable row level security/)
assert.match(migration,/with check \(\(select auth\.uid\(\)\) = user_id\)/)
assert.match(migration,/using \(\(select auth\.uid\(\)\) = 'bc6ee244-3472-422f-bbf9-d551987ee9a3'::uuid\)/)
assert.match(migration,/revoke all on table public\.activity_logs from anon, authenticated/)
assert.match(migration,/grant insert, select on table public\.activity_logs to authenticated/)
assert.doesNotMatch(migration,/grant update|grant delete/i)

assert.match(tracker,/eventType: 'page_view'/)
assert.match(tracker,/eventType: 'click'/)
assert.match(tracker,/eventType: 'submit'/)
assert.match(tracker,/eventType: 'control_change'/)
assert.doesNotMatch(tracker,/\.value/)
assert.doesNotMatch(helper,/password/i)
assert.match(shell,/ActivityTracker userId=\{userId\}/)
assert.match(shell,/eventType:'logout'/)
assert.match(login,/eventType:'login'/)
assert.match(users,/Activity Log/)
assert.match(users,/OwnerOnlyGate/)

console.log('Activity Log security and tracking regression checks passed')
