const fs=require('fs')
const assert=require('node:assert/strict')

const route=fs.readFileSync('app/api/defect/validate-upload/route.ts','utf8')
const panel=fs.readFileSync('components/DefectInputPanel.tsx','utf8')
const migration=fs.readFileSync('supabase/migrations/20261006082000_defect_ingest_validation_dedupe.sql','utf8')
const viewerEditor=fs.readFileSync('supabase/migrations/20261006083000_viewer_editor_defect_access.sql','utf8')

assert.match(route,/inlineData:\{mimeType:'application\/pdf'/)
assert.match(route,/is_defect/)
assert.match(route,/\^\[AB\]\[0-9\]\{3\}\$/)
assert.match(route,/createHash\('sha256'\)/)
assert.match(route,/defect_register_validated_file/)
assert.match(route,/storage\.from\('defect-flow-staging'\)\.remove/)
assert.match(route,/status:'duplicate'/)
assert.match(route,/status:'rejected'/)
assert.match(route,/canEditDefect\(resolveAccessRole\(profile.role,user.id\)\)/)
assert.match(panel,/\/api\/defect\/validate-upload/)
assert.doesNotMatch(panel,/rpc\('defect_register_file_upload'/)

assert.match(migration,/DIRECT_DEFECT_FILE_REGISTER_DISABLED/)
assert.match(migration,/content_sha256/)
assert.match(migration,/validation_status='accepted'/)
assert.match(migration,/defect_pdf_duplicate_ignored/)
assert.match(migration,/detail_fingerprint/)
assert.match(migration,/lower\(regexp_replace/)
assert.match(migration,/DUPLICATE_DEFECT_IN_REQUEST/)
assert.match(migration,/revoke all on function public\.defect_register_file_upload/)
assert.match(migration,/INVALID_DEFECT_INGEST_SERVER_TOKEN/)
assert.match(viewerEditor,/viewer_editor/)
assert.match(viewerEditor,/DIRECT_DEFECT_FILE_REGISTER_DISABLED/)
assert.match(viewerEditor,/detail_fingerprint/)

console.log('Defect ingest validation and duplicate protection checks passed')
