const fs=require('fs')
const assert=require('node:assert/strict')

const page=fs.readFileSync('app/calendar/page.tsx','utf8')
const component=fs.readFileSync('components/GoogleCalendarManager.tsx','utf8')
const eventsApi=fs.readFileSync('app/api/google-calendar/events/route.ts','utf8')
const statusApi=fs.readFileSync('app/api/google-calendar/status/route.ts','utf8')
const oauthStart=fs.readFileSync('app/api/google-calendar/oauth/start/route.ts','utf8')
const oauthComplete=fs.readFileSync('app/api/google-calendar/oauth/complete/route.ts','utf8')
const ownerOAuth=fs.readFileSync('lib/googleCalendarOwnerOAuth.ts','utf8')
const server=fs.readFileSync('lib/googleCalendarServer.ts','utf8')
const tokenStore=fs.readFileSync('lib/googleCalendarTokenStore.ts','utf8')
const auth=fs.readFileSync('lib/googleCalendarApiAuth.ts','utf8')
const migration=fs.readFileSync('supabase/migrations/20261006095000_google_calendar_owner_oauth_token.sql','utf8')

assert.match(page,/GoogleCalendarManager/)
assert.doesNotMatch(page,/CalendarEditor/)

assert.match(component,/ownerSetupRequired/)
assert.match(component,/เชื่อม Google ให้ระบบ/)
assert.match(component,/MAX_MONTH_EVENTS=3/)
assert.match(component,/\+\{hidden\} รายการ/)
assert.match(component,/gcal-event-title/)
assert.match(component,/canEditCalendar\(role\)/)
assert.match(component,/google_calendar_event_create/)
assert.match(component,/google_calendar_event_update/)
assert.match(component,/google_calendar_event_delete/)
assert.doesNotMatch(component,/NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_ID/)
assert.doesNotMatch(component,/accounts\.google\.com\/gsi\/client/)
assert.doesNotMatch(component,/work_calendar_save_event/)
assert.doesNotMatch(component,/work_calendar_create/)

assert.match(eventsApi,/https:\/\/www\.googleapis\.com\/calendar\/v3\/calendars\//)
assert.match(eventsApi,/method:'POST'/)
assert.match(eventsApi,/method:'PATCH'/)
assert.match(eventsApi,/method:'DELETE'/)
assert.match(eventsApi,/!auth\.editable/)
assert.match(statusApi,/googleCalendarSharedConfigured/)
assert.match(oauthStart,/auth\.role!=='owner'/)
assert.match(oauthComplete,/verifyGoogleOAuthState/)
assert.match(oauthComplete,/encryptGoogleRefreshToken/)
assert.match(oauthComplete,/storeEncryptedGoogleRefreshToken/)

assert.match(ownerOAuth,/access_type:'offline'/)
assert.match(ownerOAuth,/prompt:'consent'/)
assert.match(ownerOAuth,/aes-256-gcm/)
assert.match(ownerOAuth,/createHmac\('sha256'/)
assert.match(ownerOAuth,/GOOGLE_CALENDAR_CLIENT_SECRET/)
assert.match(server,/decryptGoogleRefreshToken/)
assert.match(server,/refreshGoogleAccessToken/)
assert.match(tokenStore,/google_calendar_owner_token_upsert/)
assert.match(tokenStore,/google_calendar_owner_token_get/)
assert.match(auth,/canAccessPath\(role,'\/calendar'\)/)

assert.match(migration,/app_private\.google_calendar_owner_token/)
assert.match(migration,/bc6ee244-3472-422f-bbf9-d551987ee9a3/)
assert.match(migration,/revoke all on function public\.google_calendar_owner_token_upsert/)
assert.match(migration,/grant execute on function public\.google_calendar_owner_token_get\(\) to authenticated/)
assert.doesNotMatch(migration,/refresh_token text not null/i)

console.log('Google Calendar owner OAuth shared-mode and compact-layout regression checks passed')
