const fs=require('fs')
const assert=require('node:assert/strict')

const page=fs.readFileSync('app/calendar/page.tsx','utf8')
const component=fs.readFileSync('components/GoogleCalendarManager.tsx','utf8')
const api=fs.readFileSync('app/api/google-calendar/events/route.ts','utf8')
const status=fs.readFileSync('app/api/google-calendar/status/route.ts','utf8')
const server=fs.readFileSync('lib/googleCalendarServer.ts','utf8')
const auth=fs.readFileSync('lib/googleCalendarApiAuth.ts','utf8')

assert.match(page,/GoogleCalendarManager/)
assert.doesNotMatch(page,/CalendarEditor/)

assert.match(component,/Transport='checking'\|'shared'\|'browser'/)
assert.match(component,/\/api\/google-calendar\/status/)
assert.match(component,/\/api\/google-calendar\/events/)
assert.match(component,/canEditCalendar\(role\)/)
assert.match(component,/MAX_MONTH_EVENTS=3/)
assert.match(component,/\+\{hidden\} รายการ/)
assert.match(component,/gcal-event-title/)
assert.doesNotMatch(component,/work_calendar_save_event/)
assert.doesNotMatch(component,/work_calendar_create/)

assert.match(api,/googleCalendarServiceFetch/)
assert.match(api,/WORK_CALENDAR_IDS/)
assert.match(api,/method:'POST'/)
assert.match(api,/method:'PATCH'/)
assert.match(api,/method:'DELETE'/)
assert.match(api,/!auth\.editable/)
assert.match(status,/googleCalendarServiceConfigured/)
assert.match(server,/GOOGLE_CALENDAR_SERVICE_ACCOUNT_EMAIL/)
assert.match(server,/GOOGLE_CALENDAR_SERVICE_ACCOUNT_PRIVATE_KEY/)
assert.match(server,/urn:ietf:params:oauth:grant-type:jwt-bearer/)
assert.match(auth,/canAccessPath\(role,'\/calendar'\)/)
assert.match(auth,/canEditCalendar\(role\)/)

assert.match(component,/NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_ID/)
assert.match(component,/https:\/\/www\.googleapis\.com\/calendar\/v3\/calendars\//)
assert.match(component,/https:\/\/www\.googleapis\.com\/auth\/calendar\.events/)
assert.match(component,/google_calendar_event_create/)
assert.match(component,/google_calendar_event_update/)
assert.match(component,/google_calendar_event_delete/)

console.log('Google Calendar shared-mode and compact-layout regression checks passed')
