const fs=require('fs')
const assert=require('node:assert/strict')
const ts=require('typescript')
const vm=require('node:vm')

function loadTs(file){
  const source=fs.readFileSync(file,'utf8')
  const output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText
  const module={exports:{}}
  vm.runInNewContext(output,{module,exports:module.exports,require})
  return module.exports
}

const access=loadTs('lib/accessControl.ts')
const shell=fs.readFileSync('components/AppShell.tsx','utf8')
const users=fs.readFileSync('app/users/page.tsx','utf8')
const roleGuard=fs.readFileSync('components/RolePermissionGuard20260927.tsx','utf8')
const migration=fs.readFileSync('supabase/migrations/20261006111500_rbac_editor_purchase_and_defect_manual_updates.sql','utf8')
const adminUsers=fs.readFileSync('supabase/functions/admin-users/index.ts','utf8')

assert.equal(access.canAccessPath('owner','/users'),true)
assert.equal(access.canAccessPath('admin','/reports/labour'),true)
assert.equal(access.canAccessPath('admin','/users'),false)
assert.equal(access.canAccessPath('viewer','/reports'),true)
assert.equal(access.canAccessPath('viewer','/reports/labour'),false)
assert.equal(access.canAccessPath('viewer','/photo-mapping'),false)
assert.equal(access.canAccessPath('viewer_editor','/schedule'),true)
assert.equal(access.canAccessPath('viewer_editor','/reports/labour'),false)
assert.equal(access.canAccessPath('defect_contributor','/defect-flow'),true)
assert.equal(access.canAccessPath('defect_contributor','/defects?building=A'),true)
assert.equal(access.canAccessPath('defect_contributor','/schedule'),false)
assert.equal(access.canAccessPath('defect_editor','/schedule'),true)
assert.equal(access.canAccessPath('defect_editor','/reports/labour'),false)
assert.equal(access.canAccessPath('purchase','/procurement'),true)
assert.equal(access.canAccessPath('purchase','/reports/labour'),false)

assert.equal(access.canEditSiteOperations('admin'),true)
assert.equal(access.canEditSiteOperations('viewer'),false)
assert.equal(access.canEditSchedule('viewer_editor'),true)
assert.equal(access.canEditSchedule('admin'),false)
assert.equal(access.canEditDefects('defect_contributor'),true)
assert.equal(access.canEditDefects('defect_editor'),true)
assert.equal(access.canEditDefects('admin'),false)
assert.equal(access.canEditProcurement('purchase'),true)
assert.equal(access.canEditProcurement('admin'),false)

assert.doesNotMatch(shell,/Labour & Payroll/)
assert.match(shell,/\['\/users','System & Access'\]/)
assert.match(shell,/User & Access/)
assert.match(shell,/Photo Mapping/)
assert.match(shell,/Data Health/)
assert.match(shell,/canViewPayroll\(presentationRole\).*Payroll Verification Record/)
assert.match(roleGuard,/canAccessPath\(role,path\)/)

assert.match(users,/value="viewer_editor"/)
assert.match(users,/value="defect_editor"/)
assert.match(users,/value="purchase"/)

assert.match(migration,/'viewer_editor'::text/)
assert.match(migration,/'defect_editor'::text/)
assert.match(migration,/'purchase'::text/)
assert.match(migration,/revoke insert,update,delete on public\.schedule_tasks from authenticated,anon/)
assert.match(migration,/revoke insert,update,delete on public\.procurement_items from authenticated,anon/)
assert.match(migration,/schedule_save_web_override/)
assert.match(migration,/p\.role in \('manager','viewer_editor'\)/)
assert.match(migration,/procurement_save_web_override/)
assert.match(migration,/p\.role in \('manager','purchase'\)/)
assert.match(migration,/site_operations_save_management_review/)
assert.match(migration,/p\.role in \('manager','admin','engineer','payroll'\)/)
assert.match(migration,/defect_submit_manual_details/)
assert.match(migration,/p\.role in \('manager','defect_contributor','defect_editor'\)/)
assert.match(migration,/insert into public\.activity_logs/)
assert.match(migration,/security_invoker=true/)

assert.match(adminUsers,/viewer_editor/)
assert.match(adminUsers,/defect_editor/)
assert.match(adminUsers,/purchase/)

console.log('RBAC and audited Web-edit regression checks passed')
