const fs=require('fs')
const assert=require('assert')

const access=fs.readFileSync('lib/accessControl.ts','utf8')
const shell=fs.readFileSync('components/AppShell.tsx','utf8')
const users=fs.readFileSync('app/users/page.tsx','utf8')
const adminUsers=fs.readFileSync('supabase/functions/admin-users/index.ts','utf8')
const migration=fs.readFileSync('supabase/migrations/20261006070000_rbac_editors_calendar_defect_inputs.sql','utf8')
const viewerEditorDefect=fs.readFileSync('supabase/migrations/20261006083000_viewer_editor_defect_access.sql','utf8')
const standardNav=(shell.match(/const standardNav: NavItem\[\] = \[([\s\S]*?)\n\]/)||[])[1]||''

for(const role of ['viewer_editor','defect_editor','purchase','defect_contributor'])assert.match(access,new RegExp(role))
assert.match(access,/OWNER_ONLY_PREFIXES=\['\/photo-mapping','\/data-health','\/data-house','\/users'\]/)
assert.match(access,/canEditSiteOperations/)
assert.match(access,/canEditCalendar/)
assert.match(access,/canEditSchedule/)
assert.match(access,/canEditDefect/)
assert.match(access,/return role==='owner'\|\|role==='defect_editor'/)
assert.match(access,/canEditProcurement/)
assert.doesNotMatch(standardNav,/\/reports\/labour/)
assert.match(standardNav,/\['\/reports', 'Site Operations'\]/)
assert.match(shell,/\['\/users','System & Access'\]/)
assert.match(shell,/href="\/photo-mapping"/)
assert.match(shell,/href="\/data-health"/)
for(const role of ['viewer_editor','defect_editor','purchase'])assert.match(users,new RegExp('option value="'+role+'"'))
assert.match(adminUsers,/viewer_editor/);assert.match(adminUsers,/defect_editor/);assert.match(adminUsers,/purchase/)
assert.match(migration,/CALENDAR_DAILY_CREATE_LIMIT_3/)
assert.match(migration,/defect-flow-staging/)
assert.match(migration,/defect_manual_update_apply/)
assert.match(migration,/activity_logs/)
assert.match(viewerEditorDefect,/viewer_editor/)
assert.match(viewerEditorDefect,/defect_register_file_upload/)
assert.match(viewerEditorDefect,/defect_manual_update_apply/)
console.log('Canonical RBAC and guarded editor static checks passed')