const fs=require('fs')
const assert=require('assert')

const access=fs.readFileSync('lib/accessControl.ts','utf8')
const shell=fs.readFileSync('components/AppShell.tsx','utf8')
const boundary=fs.readFileSync('components/AccessBoundary.tsx','utf8')
const labour=fs.readFileSync('app/reports/labour/page.tsx','utf8')
const users=fs.readFileSync('app/users/page.tsx','utf8')
const visual=fs.readFileSync('app/api/ai/visual-match/route.ts','utf8')
const migration=fs.readFileSync('supabase/migrations/20261005033728_rbac_v2_owner_admin_viewer_defect.sql','utf8')
const guardMigration=fs.readFileSync('supabase/migrations/20261005033851_rbac_internal_labour_payroll_guard.sql','utf8')
const roleBridge=fs.readFileSync('supabase/migrations/20261005034044_rbac_owner_role_bridge.sql','utf8')
const adminUsers=fs.readFileSync('supabase/functions/admin-users/index.ts','utf8')

assert.match(access,/defect_contributor/)
assert.match(access,/OWNER_ONLY_PREFIXES=\['\/photo-mapping','\/data-health','\/data-house','\/users'\]/)
assert.match(access,/role==='viewer'.*REPORT_WRITE_PATHS/)
assert.equal((access.match(/role==='defect_contributor'/g)||[]).length>=1,true)
assert.match(access,/value==='\/defect-flow'.*value==='\/defects'/)
assert.match(boundary,/\/api\/access-control\?path=/)
assert.match(boundary,/allowedPath===path/)
assert.match(shell,/Defect Contributor/)
assert.match(shell,/canViewPayroll\(accessRole\)\?'Payroll Verification Record':'Labour'/)
assert.match(labour,/payrollAllowed\?readAllPages<PayrollRecord>/)
assert.match(labour,/payrollAllowed\?readAllPages<PayrollItem>/)
assert.match(labour,/const canVerify=canManageLabour\(accessRole\)/)
assert.match(users,/option value="defect_contributor">Defect Contributor/)
assert.match(users,/row\.user_id === OWNER_USER_ID/)
assert.match(visual,/user\.id!==OWNER_USER_ID\|\|profile\.role!=='manager'/)

assert.match(migration,/profiles_role_check[\s\S]*'admin'[\s\S]*'viewer'[\s\S]*'defect_contributor'/)
assert.match(migration,/drop policy if exists profiles_update_self/)
assert.match(migration,/revoke insert,update,delete,truncate,references,trigger on public\.profiles from authenticated/)
assert.match(migration,/p\.role<>'defect_contributor'/)
assert.match(migration,/v_role:='viewer';[\s\S]*v_active:=false/)
assert.match(migration,/private\.can_manage_labour_payroll/)
assert.match(migration,/p\.role in \('manager','admin','engineer','payroll'\)/)
assert.match(migration,/revoke select on public\.v_schedule_snapshot_days from anon/)
assert.match(migration,/CLIENT_PAYROLL_MONEY_NOT_ALLOWED/)
assert.match(migration,/PAYROLL_RULES_NOT_APPROVED/)
assert.match(migration,/revoke insert,update,delete on public\.payroll_verification_records from authenticated,anon/)
assert.match(migration,/labour_confirm_headcount/)
assert.match(guardMigration,/labour_payroll_guard_row\(\) security definer/)
assert.match(roleBridge,/owner_set_profile_role/)
assert.match(roleBridge,/OWNER_ONLY/)
assert.match(adminUsers,/VALID_ROLES = new Set\(\['manager', 'admin', 'viewer', 'defect_contributor'/)
assert.match(adminUsers,/const \{ error: profileError \} = await admin\.from\('profiles'\)\.update\(/)

console.log('RBAC static regression checks passed')
