const fs=require('fs')
const assert=require('node:assert/strict')
const ts=require('typescript')
const vm=require('node:vm')

function loadTs(file){const source=fs.readFileSync(file,'utf8');const output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;const module={exports:{}};vm.runInNewContext(output,{module,exports:module.exports,require});return module.exports}

const previewSource=fs.readFileSync('lib/rolePreview.ts','utf8')
const shell=fs.readFileSync('components/AppShell.tsx','utf8')
const labour=fs.readFileSync('app/reports/labour/page.tsx','utf8')
const preview=loadTs('lib/rolePreview.ts')
const access=loadTs('lib/accessControl.ts')

assert.deepEqual([...preview.previewTargetsFor('owner')],['admin','viewer','viewer_editor','defect_contributor','defect_editor','purchase'])
assert.deepEqual([...preview.previewTargetsFor('admin')],['viewer','viewer_editor','defect_contributor','defect_editor','purchase'])
assert.deepEqual([...preview.previewTargetsFor('viewer')],[])
assert.equal(access.canAccessPath('viewer','/reports'),true)
assert.equal(access.canAccessPath('viewer','/reports/labour'),true)
assert.equal(access.canAccessPath('viewer','/users'),false)
assert.equal(access.canAccessPath('defect_contributor','/defect-flow'),true)
assert.equal(access.canAccessPath('defect_contributor','/materials'),false)
assert.equal(access.canEditSchedule('viewer_editor'),true)
assert.equal(access.canEditCalendar('viewer_editor'),true)
assert.equal(access.canEditProcurement('purchase'),true)
assert.equal(access.canEditDefect('defect_editor'),true)
assert.equal(access.canEditDefect('viewer_editor'),false)
assert.equal(access.canEditSiteOperations('admin'),true)
assert.equal(access.canViewPayroll('viewer'),true)
assert.equal(access.canViewPayroll('admin'),true)
assert.match(previewSource,/sessionStorage\.getItem\(ROLE_PREVIEW_STORAGE_KEY\)/)
assert.doesNotMatch(previewSource,/localStorage/)
assert.match(shell,/System & Access/)
assert.match(shell,/แรงงานและค่าแรง':'แรงงาน'/)
assert.match(labour,/const payrollAllowed=canViewPayroll\(nextAccessRole\)/)
console.log('Role preview and canonical RBAC regression checks passed')