'use client'

import { useEffect,useRef,useState } from 'react'
import { createPortal } from 'react-dom'
import { getSupabase } from '@/lib/supabase'

type PhotoRow={id:string;drive_file_id:string;drive_folder_id:string|null;project_id:string;schedule_task_id:string|null;file_name:string;photo_date:string;phase:string|null;verified_at:string|null;indexed_at:string|null}
type TaskRow={id:string;project_id:string;source_task_no:string|null;task_name:string;area:string|null;category:string|null}
type ProjectRow={id:string;code:string;name:string}
type FeedbackRow={photo_id:string;task_id:string;status:'approved'|'rejected';note:string|null;reviewed_by:string|null;reviewed_at:string}
type AIScore={photo_id:string;score:number;detected_work:string|null;reason:string|null;model:string;analyzed_at:string}
type Relation='approved'|'direct'|'similar'|'plot'
type Candidate=PhotoRow&{relation:Relation;similarity:number;sourceTask?:TaskRow;ai?:AIScore;learning?:number;learningSamples?:number}
type EditorState={photo:PhotoRow;targetTask:TaskRow;project:ProjectRow;tasks:TaskRow[];alternatives:Candidate[];ai:AIScore|null}
type EditorActions={approve:(photoId:string,taskId:string,note?:string)=>Promise<void>;reject:(photoId:string,taskId:string,note?:string)=>Promise<void>;replace:(oldPhotoId:string,newPhotoId:string,taskId:string)=>Promise<void>;remap:(photoId:string,currentTaskId:string,newTaskId:string,note?:string)=>Promise<void>}

const PAGE=500
const AI_CANDIDATES=8
const FAMILY_GROUPS=[
  ['ฝ้า','เพดาน','ชายคา','ceiling'],['กระเบื้อง','tile'],['สี','paint','skim','ฉาบ'],
  ['ท่อ','ระบายน้ำ','ประปา','สุขาภิบาล','drain','plumbing'],['แอร์','ปรับอากาศ','fcu','ccu','aircon','air conditioning'],
  ['ราว','กันตก','railing'],['สระ','pool','บันไดลงสระ','สไลเดอร์'],['ประตู','หน้าต่าง','อลูมิเนียม','กระจก','door','window','aluminium','glass'],
  ['หลังคา','รางน้ำ','roof','gutter','vg'],['ไฟฟ้า','electrical','electric'],['โครงสร้าง','คอนกรีต','เทพื้น','structure','concrete'],['steam','ห้อง steam'],
] as const

function norm(v:string|null|undefined){return String(v||'').toLowerCase().replace(/[._()\-–—/\\,:;]+/g,' ').replace(/\s+/g,' ').trim()}
function tokens(v:string|null|undefined){return new Set(norm(v).split(' ').filter(x=>x.length>1))}
function family(t:TaskRow|undefined){if(!t)return-1;const text=norm(`${t.task_name} ${t.area||''} ${t.category||''}`);return FAMILY_GROUPS.findIndex(g=>g.some(k=>text.includes(norm(k))))}
function taskSimilarity(a:TaskRow,b:TaskRow){if(a.id===b.id)return 1;const fa=family(a),fb=family(b);const at=tokens(`${a.task_name} ${a.area||''}`),bt=tokens(`${b.task_name} ${b.area||''}`);const intersection=[...at].filter(x=>bt.has(x)).length;const union=new Set([...at,...bt]).size;return(fa>=0&&fa===fb?.55:0)+(a.area&&b.area&&norm(a.area)===norm(b.area)?.2:0)+(a.category&&b.category&&norm(a.category)===norm(b.category)?.1:0)+((union?intersection/union:0)*.15)}
function newest(a:PhotoRow,b:PhotoRow){return b.photo_date.localeCompare(a.photo_date)||String(b.indexed_at||'').localeCompare(String(a.indexed_at||''))||b.id.localeCompare(a.id)}
function hash(v:string){let h=2166136261;for(let i=0;i<v.length;i++){h^=v.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rotateRecent<T>(rows:T[],seed:string,windowSize=16){const head=rows.slice(0,windowSize),tail=rows.slice(windowSize);if(head.length<2)return rows;const offset=hash(seed)%head.length;return[...head.slice(offset),...head.slice(0,offset),...tail]}
function dateLabel(v:string){const[y,m,d]=v.split('-');return y&&m&&d?`${d}/${m}/${Number(y)+543}`:v}
function phaseLabel(v:string|null){if(v==='before')return'ก่อนทำ';if(v==='after')return'หลังทำ';if(v==='during')return'ระหว่างทำ';return'รูปหน้างาน'}
function pairKey(photoId:string,taskId:string){return`${photoId}|${taskId}`}
function inPeriod(p:PhotoRow,start:string,end:string){return(!start||p.photo_date>=start)&&(!end||p.photo_date<=end)}
function setText(el:Element|null,value:string){if(el&&el.textContent!==value)el.textContent=value}
function mode(){const x=[...document.querySelectorAll<HTMLSelectElement>('.ep-filter select')];return x.find(s=>[...s.options].some(o=>o.value==='before_after'))?.value||'latest'}
function period(){const x=[...document.querySelectorAll<HTMLInputElement>('.ep-filter input[type="date"]')];return{start:x[0]?.value||'',end:x[1]?.value||''}}
function codeFromSlide(slide:Element){return(slide.querySelector('.ep-eyebrow')?.textContent||'').split('•')[0]?.trim()||''}
function codeFromCard(card:Element,projects:ProjectRow[]){const name=card.querySelector('.ep-cover-title b')?.textContent?.trim()||'';return projects.find(p=>p.name.trim()===name)?.code||''}
function fileId(img:HTMLImageElement){try{const u=new URL(img.src,window.location.origin);return u.pathname==='/api/drive-photo'?u.searchParams.get('fileId')||'':''}catch{return''}}
function taskFromSlide(slide:Element,project:ProjectRow,tasks:TaskRow[]){const name=slide.querySelector('h2')?.textContent?.trim()||'';if(!name)return null;const area=(slide.querySelector('header p')?.textContent||'').split('•')[0]?.trim()||'';const list=tasks.filter(t=>t.project_id===project.id&&norm(t.task_name)===norm(name));if(list.length<=1)return list[0]||null;return list.find(t=>t.area&&norm(area).includes(norm(t.area)))||list[0]}
async function allPhotos(s:any){let rows:PhotoRow[]=[];for(let from=0;;from+=PAGE){const r=await s.from('drive_photo_index').select('id,drive_file_id,drive_folder_id,project_id,schedule_task_id,file_name,photo_date,phase,verified_at,indexed_at').eq('is_active',true).order('photo_date',{ascending:false}).order('indexed_at',{ascending:false}).range(from,from+PAGE-1);if(r.error)throw r.error;const b=(r.data||[]) as PhotoRow[];rows=rows.concat(b);if(b.length<PAGE)break}return rows}
function relationFor(photo:PhotoRow,target:TaskRow,taskById:Map<string,TaskRow>):Exclude<Relation,'approved'>{if(photo.schedule_task_id===target.id)return'direct';const source=photo.schedule_task_id?taskById.get(photo.schedule_task_id):undefined;return source&&taskSimilarity(target,source)>=.38?'similar':'plot'}
function pushUnique(target:Candidate[],rows:Candidate[],limit:number){for(const row of rows){if(target.length>=limit)break;if(!target.some(x=>x.id===row.id))target.push(row)}}

function learningBias(candidate:Candidate,target:TaskRow,userId:string,feedbackRows:FeedbackRow[],photoById:Map<string,PhotoRow>,taskById:Map<string,TaskRow>){
  if(!userId)return{score:0,samples:0}
  let sum=0,weight=0,samples=0
  const candidateSource=candidate.sourceTask||(candidate.schedule_task_id?taskById.get(candidate.schedule_task_id):undefined)
  for(const f of feedbackRows){
    if(f.reviewed_by!==userId)continue
    const oldTarget=taskById.get(f.task_id),oldPhoto=photoById.get(f.photo_id);if(!oldTarget||!oldPhoto)continue
    const sameFamily=family(target)>=0&&family(target)===family(oldTarget),targetSim=taskSimilarity(target,oldTarget)
    if(oldTarget.id!==target.id&&!sameFamily&&targetSim<.38)continue
    const oldRelation=relationFor(oldPhoto,oldTarget,taskById);let feature=0
    if(oldRelation===candidate.relation)feature+=.45
    if((oldPhoto.phase||'other')===(candidate.phase||'other'))feature+=.20
    const oldSource=oldPhoto.schedule_task_id?taskById.get(oldPhoto.schedule_task_id):undefined
    if(candidateSource&&oldSource&&family(candidateSource)>=0&&family(candidateSource)===family(oldSource))feature+=.20
    if(oldTarget.id===target.id)feature+=.30;else if(sameFamily)feature+=.15
    if(feature<=0)continue
    sum+=(f.status==='approved'?1:-1)*feature;weight+=feature;samples++
  }
  if(!weight||!samples)return{score:0,samples:0}
  const shrink=Math.min(1,samples/4);const score=Math.max(-14,Math.min(14,Math.round((sum/weight)*14*shrink)))
  return{score,samples}
}

function buildCandidates(project:ProjectRow,target:TaskRow,photos:PhotoRow[],taskById:Map<string,TaskRow>,feedback:Map<string,FeedbackRow>,start:string,end:string){
  const projectPhotos=photos.filter(p=>p.project_id===project.id&&inPeriod(p,start,end)).sort(newest)
  const rejected=new Set(projectPhotos.filter(p=>feedback.get(pairKey(p.id,target.id))?.status==='rejected').map(p=>p.id))
  const approved=projectPhotos.filter(p=>feedback.get(pairKey(p.id,target.id))?.status==='approved').map(p=>({...p,relation:'approved' as const,similarity:1,sourceTask:target}))
  const direct=projectPhotos.filter(p=>!rejected.has(p.id)&&p.schedule_task_id===target.id&&!approved.some(a=>a.id===p.id)).map(p=>({...p,relation:'direct' as const,similarity:1,sourceTask:target}))
  const similar=projectPhotos.filter(p=>!rejected.has(p.id)&&p.schedule_task_id&&p.schedule_task_id!==target.id&&!approved.some(a=>a.id===p.id)).map(p=>{const sourceTask=taskById.get(String(p.schedule_task_id));return{...p,relation:'similar' as const,similarity:sourceTask?taskSimilarity(target,sourceTask):0,sourceTask}}).filter(p=>p.similarity>=.38).sort((a,b)=>b.similarity-a.similarity||newest(a,b))
  const unmatched=rotateRecent(projectPhotos.filter(p=>!rejected.has(p.id)&&!p.schedule_task_id&&!approved.some(a=>a.id===p.id)).map(p=>({...p,relation:'plot' as const,similarity:0})),`${target.id}:unmatched`)
  const other=rotateRecent(projectPhotos.filter(p=>!rejected.has(p.id)&&p.schedule_task_id&&p.schedule_task_id!==target.id&&!approved.some(a=>a.id===p.id)&&!similar.some(s=>s.id===p.id)).map(p=>({...p,relation:'plot' as const,similarity:0,sourceTask:taskById.get(String(p.schedule_task_id))})),`${target.id}:mapped`)
  const pool:Candidate[]=[];pushUnique(pool,approved,AI_CANDIDATES);pushUnique(pool,direct,AI_CANDIDATES);pushUnique(pool,similar,AI_CANDIDATES);pushUnique(pool,unmatched,AI_CANDIDATES);pushUnique(pool,other,AI_CANDIDATES);return pool
}
function relationPriority(r:Relation){return r==='approved'?100:r==='direct'?18:r==='similar'?10:0}
function rank(candidate:Candidate,maxDate:string){if(candidate.relation==='approved')return 1000;const ai=Number(candidate.ai?.score||0);const days=Math.max(0,Math.round((new Date(`${maxDate}T00:00:00Z`).getTime()-new Date(`${candidate.photo_date}T00:00:00Z`).getTime())/86400000));const recency=Math.max(0,8-Math.min(8,days));return ai+recency+relationPriority(candidate.relation)+(candidate.learning||0)}
function selectPhotos(candidates:Candidate[],scores:Map<string,AIScore>,userId:string,feedbackRows:FeedbackRow[],photoById:Map<string,PhotoRow>,taskById:Map<string,TaskRow>,target:TaskRow){
  const enriched=candidates.map(c=>{const learn=learningBias(c,target,userId,feedbackRows,photoById,taskById);return{...c,ai:scores.get(c.id),learning:learn.score,learningSamples:learn.samples}});const maxDate=enriched.reduce((m,p)=>!m||p.photo_date>m?p.photo_date:m,'')
  const approved=enriched.filter(x=>x.relation==='approved').sort(newest)
  const scored=enriched.filter(x=>x.relation!=='approved'&&x.ai&&Number(x.ai.score)>=35&&Number(x.ai.score)+(x.learning||0)>=40).sort((a,b)=>rank(b,maxDate)-rank(a,maxDate)||newest(a,b))
  const fallback=enriched.filter(x=>x.relation!=='approved'&&!scored.some(s=>s.id===x.id)).sort((a,b)=>rank(b,maxDate)-rank(a,maxDate)||newest(a,b))
  const out:Candidate[]=[];pushUnique(out,approved,4);pushUnique(out,scored,4);if(!scores.size)pushUnique(out,fallback,4);return out.slice(0,4)
}
function relationLabel(p:Candidate){if(p.relation==='approved')return'ยืนยันโดย Golf';if(p.ai)return`AI Match ${Math.round(Number(p.ai.score))}%`;if(p.relation==='direct')return'ตรง Task';if(p.relation==='similar')return'งานใกล้เคียง';return'Plot fallback'}
function detail(p:Candidate){if(p.ai?.detected_work)return p.ai.detected_work;if(p.sourceTask&&p.relation!=='direct'&&p.relation!=='approved')return p.sourceTask.task_name;return p.file_name}

export default function ExecutiveAIVisualMatcherV2(){
  const [editor,setEditor]=useState<EditorState|null>(null);const[editorTask,setEditorTask]=useState('');const[editorNote,setEditorNote]=useState('');const[editorSaving,setEditorSaving]=useState(false);const[editorMessage,setEditorMessage]=useState('');const[toast,setToast]=useState('')
  const actionsRef=useRef<EditorActions|null>(null)

  useEffect(()=>{
    let dead=false,observer:MutationObserver|null=null,scheduled=false,cleanup:(()=>void)|undefined
    const s=getSupabase(),aiCache=new Map<string,Map<string,AIScore>>(),aiPending=new Set<string>(),aiAttempted=new Set<string>(),aiErrors=new Map<string,string>()
    const setup=async()=>{
      const[photos,tr,pr,fr,auth]=await Promise.all([allPhotos(s),s.from('v_schedule_tasks').select('id,project_id,source_task_no,task_name,area,category'),s.from('projects').select('id,code,name').eq('active',true),s.from('photo_task_feedback').select('photo_id,task_id,status,note,reviewed_by,reviewed_at'),s.auth.getUser()]);if(dead||tr.error||pr.error)return
      const tasks=(tr.data||[]) as TaskRow[],projects=(pr.data||[]) as ProjectRow[];let feedbackRows=(fr.data||[]) as FeedbackRow[];const user=auth.data.user;let role='';if(user){const r=await s.from('profiles').select('role').eq('user_id',user.id).maybeSingle();role=r.data?.role||''}const editable=Boolean(user&&['manager','engineer'].includes(role)),userId=user?.id||''
      const taskById=new Map(tasks.map(t=>[t.id,t])),projectByCode=new Map(projects.map(p=>[p.code,p])),photoById=new Map(photos.map(p=>[p.id,p])),photoByFile=new Map(photos.map(p=>[p.drive_file_id,p])),feedback=new Map(feedbackRows.map(f=>[pairKey(f.photo_id,f.task_id),f]))

      const schedule=()=>{if(dead||scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;decorate()})}
      const saveFeedback=async(photoId:string,taskId:string,status:'approved'|'rejected',note='')=>{if(!editable||!user)throw new Error('บัญชีนี้ไม่มีสิทธิ์แก้ Photo Mapping');const now=new Date().toISOString(),row={photo_id:photoId,task_id:taskId,status,note:note.trim()||null,reviewed_by:user.id,reviewed_at:now,updated_at:now};const r=await s.from('photo_task_feedback').upsert(row,{onConflict:'photo_id,task_id'});if(r.error)throw r.error;const local:FeedbackRow={photo_id:photoId,task_id:taskId,status,note:row.note,reviewed_by:user.id,reviewed_at:now};feedback.set(pairKey(photoId,taskId),local);feedbackRows=[...feedbackRows.filter(x=>!(x.photo_id===photoId&&x.task_id===taskId)),local];setToast(status==='approved'?'บันทึกแล้ว ✓ AI จะให้น้ำหนักรูปแบบนี้มากขึ้น':'บันทึกแล้ว ✕ AI จะลด/ตัด Candidate ลักษณะนี้');window.setTimeout(()=>setToast(''),2200);schedule()}
      const approve=(p:string,t:string,n='')=>saveFeedback(p,t,'approved',n),reject=(p:string,t:string,n='')=>saveFeedback(p,t,'rejected',n)
      const replace=async(oldId:string,newId:string,t:string)=>{await reject(oldId,t,'แทนที่ระหว่าง Executive Presentation');await approve(newId,t,'เลือกแทนระหว่าง Executive Presentation')}
      const remap=async(photoId:string,currentTaskId:string,newTaskId:string,note='')=>{if(!editable||!user)throw new Error('บัญชีนี้ไม่มีสิทธิ์แก้ Photo Mapping');const photo=photoById.get(photoId),newTask=taskById.get(newTaskId);if(!photo||!newTask||newTask.project_id!==photo.project_id)throw new Error('Task ที่เลือกไม่ตรง Plot');const now=new Date().toISOString(),r=await s.from('drive_photo_index').update({schedule_task_id:newTaskId,match_method:'manual',match_score:1,verified_by:user.id,verified_at:now,mapping_note:note.trim()||'แก้จาก Executive Presentation',updated_at:now}).eq('id',photoId);if(r.error)throw r.error;photo.schedule_task_id=newTaskId;photo.verified_at=now;if(newTaskId===currentTaskId)await approve(photoId,currentTaskId,note||'ยืนยัน Mapping หลัก');else await reject(photoId,currentTaskId,note||`แก้ Mapping เป็น ${newTask.task_name}`);schedule()}
      actionsRef.current={approve,reject,replace,remap}

      const requestAI=async(target:TaskRow,candidates:Candidate[])=>{if(!editable||!user)return;const ids=candidates.filter(x=>x.relation!=='approved').slice(0,AI_CANDIDATES).map(x=>x.id);if(!ids.length)return;const signature=`${target.id}|${ids.join(',')}`;if(aiAttempted.has(signature))return;aiAttempted.add(signature);aiPending.add(signature);aiErrors.delete(target.id);schedule();try{const session=await s.auth.getSession();if(!session.data.session?.access_token)throw new Error('auth_session_missing');const response=await fetch('/api/ai/visual-match',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${session.data.session.access_token}`},body:JSON.stringify({taskId:target.id,candidates:ids.map(photoId=>({photoId}))})});const json=await response.json().catch(()=>null) as any;if(!response.ok||!json?.ok)throw new Error(json?.error||`AI ${response.status}`);const map=aiCache.get(target.id)||new Map<string,AIScore>();for(const row of(json.results||[]) as AIScore[])map.set(row.photo_id,row);aiCache.set(target.id,map)}catch(e){aiErrors.set(target.id,e instanceof Error?e.message:'AI unavailable')}finally{aiPending.delete(signature);schedule()}}

      const decorateControls=(figure:HTMLElement,photo:Candidate,target:TaskRow)=>{figure.dataset.photoId=photo.id;figure.dataset.taskId=target.id;let bar=figure.querySelector<HTMLElement>('.ai-photo-actionbar');if(!bar){bar=document.createElement('div');bar.className='ai-photo-actionbar';for(const [action,label] of [['approve','✓ ใช้'],['edit','✎ แก้'],['reject','✕ ไม่ตรง']] as const){const b=document.createElement('button');b.type='button';b.dataset.aiAction=action;b.textContent=label;bar.appendChild(b)}figure.appendChild(bar)}bar.style.display=editable?'flex':'none';const f=feedback.get(pairKey(photo.id,target.id));const approveBtn=bar.querySelector<HTMLButtonElement>('[data-ai-action="approve"]'),rejectBtn=bar.querySelector<HTMLButtonElement>('[data-ai-action="reject"]');if(approveBtn){approveBtn.textContent=f?.status==='approved'?'✓ ใช้อยู่':'✓ ใช้';approveBtn.classList.toggle('active',f?.status==='approved')}if(rejectBtn){rejectBtn.textContent='✕ ไม่ตรง';rejectBtn.classList.toggle('active-reject',f?.status==='rejected')}}

      const applyCover=()=>{const{start,end}=period();document.querySelectorAll<HTMLElement>('.ep-overview .ep-card').forEach(card=>{const code=codeFromCard(card,projects);if(!code||code.startsWith('CONDO-'))return;const project=projectByCode.get(code);if(!project)return;const p=photos.filter(x=>x.project_id===project.id&&inPeriod(x,start,end)).sort(newest)[0],img=card.querySelector<HTMLImageElement>('.ep-cover img');if(p&&img&&img.dataset.aiCoverFile!==p.drive_file_id){img.src=`/api/drive-photo?fileId=${encodeURIComponent(p.drive_file_id)}`;img.alt=p.file_name;img.dataset.aiCoverFile=p.drive_file_id;if(p.drive_folder_id)img.dataset.photoFolderUrl=`https://drive.google.com/drive/folders/${p.drive_folder_id}`}})}
      const applyBeforeAfter=()=>{const slide=document.querySelector<HTMLElement>('.ep-stage .ep-slide:not(.condo-slide)');if(!slide)return;const project=projectByCode.get(codeFromSlide(slide));if(!project)return;const target=taskFromSlide(slide,project,tasks);if(!target)return;slide.querySelectorAll<HTMLElement>('.ep-photo-grid figure').forEach(figure=>{const img=figure.querySelector<HTMLImageElement>('img');if(!img)return;const p=photoByFile.get(fileId(img));if(!p)return;decorateControls(figure,{...p,relation:p.schedule_task_id===target.id?'direct':'plot',similarity:0},target)})}
      const applyLatest=()=>{const slide=document.querySelector<HTMLElement>('.ep-stage .ep-slide:not(.condo-slide)');if(!slide)return;const project=projectByCode.get(codeFromSlide(slide));if(!project)return;const target=taskFromSlide(slide,project,tasks);if(!target)return;const{start,end}=period(),pool=buildCandidates(project,target,photos,taskById,feedback,start,end),scores=aiCache.get(target.id)||new Map<string,AIScore>(),selection=selectPhotos(pool,scores,userId,feedbackRows,photoById,taskById,target);void requestAI(target,pool)
        let grid=slide.querySelector<HTMLElement>('.ep-photo-grid'),empty=slide.querySelector<HTMLElement>('.ep-photo-empty');if(!selection.length){if(grid)grid.innerHTML='';if(empty)setText(empty.querySelector('b'),'ยังไม่พบรูปที่เหมาะกับงานนี้');return}if(!grid&&empty){grid=document.createElement('div');grid.className='ep-photo-grid';empty.replaceWith(grid)}if(!grid)return
        while(grid.children.length<selection.length){const f=document.createElement('figure');f.innerHTML='<img alt=""><figcaption><div><b></b><span></span></div><span></span></figcaption>';grid.appendChild(f)}while(grid.children.length>selection.length)grid.lastElementChild?.remove();grid.className=`ep-photo-grid count-${selection.length} ai-visual-grid`
        const enrichedPool=pool.map(c=>{const learn=learningBias(c,target,userId,feedbackRows,photoById,taskById);return{...c,ai:scores.get(c.id),learning:learn.score,learningSamples:learn.samples}}),alternatives=enrichedPool.filter(x=>!selection.some(s=>s.id===x.id)&&feedback.get(pairKey(x.id,target.id))?.status!=='rejected').sort((a,b)=>(Number(b.ai?.score||0)+(b.learning||0))-(Number(a.ai?.score||0)+(a.learning||0))||newest(a,b)).slice(0,6)
        selection.forEach((photo,index)=>{const figure=grid!.children[index] as HTMLElement,img=figure.querySelector<HTMLImageElement>('img'),caption=figure.querySelector<HTMLElement>('figcaption');if(!img||!caption)return;if(img.dataset.aiPhotoFile!==photo.drive_file_id){img.src=`/api/drive-photo?fileId=${encodeURIComponent(photo.drive_file_id)}`;img.alt=photo.file_name;img.dataset.aiPhotoFile=photo.drive_file_id}if(photo.drive_folder_id)img.dataset.photoFolderUrl=`https://drive.google.com/drive/folders/${photo.drive_folder_id}`;const learn=(photo.learning||0);setText(caption.querySelector('div b'),`${phaseLabel(photo.phase)} • ${relationLabel(photo)}${learn?` • เรียนรู้ ${learn>0?'+':''}${learn}`:''}`);setText(caption.querySelector('div span'),detail(photo));setText(caption.querySelector(':scope > span:last-child'),dateLabel(photo.photo_date));decorateControls(figure,photo,target)})
        let status=slide.querySelector<HTMLElement>('.ai-visual-status');if(!status){status=document.createElement('div');status.className='ai-visual-status';slide.querySelector('.ep-photo-head')?.insertAdjacentElement('afterend',status)}const pending=[...aiPending].some(k=>k.startsWith(`${target.id}|`)),err=aiErrors.get(target.id),learnCount=feedbackRows.filter(f=>f.reviewed_by===userId).length;setText(status,pending?'AI กำลังดูรูปและประเมิน Visual Similarity…':err?`AI Visual ยังใช้ไม่ได้ (${err}) • ใช้ Mapping + Feedback ที่เรียนรู้ ${learnCount} รายการชั่วคราว`:`AI Visual Match พร้อม • เรียนรู้จาก Use / Not match ของ Golf ${learnCount} รายการ • กดปุ่มใต้รูปได้ทันที`)
      }
      function decorate(){applyCover();if(mode()==='latest')applyLatest();else applyBeforeAfter()}

      const click=(event:MouseEvent)=>{const button=(event.target as Element|null)?.closest<HTMLButtonElement>('[data-ai-action]');if(!button)return;const figure=button.closest<HTMLElement>('figure[data-photo-id][data-task-id]');if(!figure)return;event.preventDefault();event.stopPropagation();const photo=photoById.get(figure.dataset.photoId||''),target=taskById.get(figure.dataset.taskId||'');if(!photo||!target)return;const project=projects.find(p=>p.id===photo.project_id);if(!project)return;const action=button.dataset.aiAction
        if(action==='approve'||action==='reject'){button.disabled=true;const fn=action==='approve'?approve:reject;fn(photo.id,target.id,action==='approve'?'ยืนยันระหว่าง Executive Presentation':'ไม่ตรงงานระหว่าง Executive Presentation').catch(e=>setToast(`บันทึกไม่สำเร็จ: ${e instanceof Error?e.message:'unknown'}`)).finally(()=>{button.disabled=false});return}
        if(action==='edit'){const{start,end}=period(),pool=buildCandidates(project,target,photos,taskById,feedback,start,end),scores=aiCache.get(target.id)||new Map<string,AIScore>(),alternatives=pool.map(c=>{const learn=learningBias(c,target,userId,feedbackRows,photoById,taskById);return{...c,ai:scores.get(c.id),learning:learn.score,learningSamples:learn.samples}}).filter(x=>x.id!==photo.id&&feedback.get(pairKey(x.id,target.id))?.status!=='rejected').sort((a,b)=>(Number(b.ai?.score||0)+(b.learning||0))-(Number(a.ai?.score||0)+(a.learning||0))||newest(a,b)).slice(0,6);setEditor({photo,targetTask:target,project,tasks:tasks.filter(t=>t.project_id===project.id&&t.source_task_no!=='1'),alternatives,ai:scores.get(photo.id)||null});setEditorTask(photo.schedule_task_id||target.id);setEditorNote('');setEditorMessage('')}
      }
      decorate();const root=document.querySelector('.ep-stage')||document.body;observer=new MutationObserver(schedule);observer.observe(root,{subtree:true,childList:true});document.addEventListener('click',click);document.addEventListener('change',schedule,true);cleanup=()=>{document.removeEventListener('click',click);document.removeEventListener('change',schedule,true)}
    }
    setup().catch(e=>setToast(`AI Photo setup error: ${e instanceof Error?e.message:'unknown'}`));return()=>{dead=true;observer?.disconnect();cleanup?.();actionsRef.current=null}
  },[])

  const run=async(action:'approve'|'reject'|'remap',alternative?:string)=>{if(!editor||!actionsRef.current)return;setEditorSaving(true);setEditorMessage('');try{if(action==='approve')await actionsRef.current.approve(editor.photo.id,editor.targetTask.id,editorNote||'ยืนยันจากหน้าพรีเซนต์');if(action==='reject')await actionsRef.current.reject(editor.photo.id,editor.targetTask.id,editorNote||'ไม่ตรงงานจากหน้าพรีเซนต์');if(action==='remap')await actionsRef.current.remap(editor.photo.id,editor.targetTask.id,editorTask,editorNote);if(alternative)await actionsRef.current.replace(editor.photo.id,alternative,editor.targetTask.id);setEditor(null)}catch(e){setEditorMessage(e instanceof Error?e.message:'บันทึกไม่สำเร็จ')}finally{setEditorSaving(false)}}

  const modal=editor&&typeof document!=='undefined'?createPortal(<div className="ai-editor-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!editorSaving)setEditor(null)}}><section className="ai-editor-modal" role="dialog" aria-modal="true"><header><div><span>LIVE PHOTO CORRECTION</span><h3>{editor.targetTask.task_name}</h3><p>{editor.project.code} • {editor.targetTask.area||'-'}</p></div><button className="button" disabled={editorSaving} onClick={()=>setEditor(null)}>ปิด</button></header><div className="ai-editor-body"><div className="ai-editor-current"><img src={`/api/drive-photo?fileId=${encodeURIComponent(editor.photo.drive_file_id)}&size=1200`} alt={editor.photo.file_name}/><div className="ai-editor-ai"><b>{editor.ai?`AI Match ${Math.round(Number(editor.ai.score))}%`:'ยังไม่มีคะแนน AI'}</b><span>{editor.ai?.detected_work||editor.photo.file_name}</span>{editor.ai?.reason&&<small>{editor.ai.reason}</small>}</div><div className="ai-editor-buttons"><button className="button primary" disabled={editorSaving} onClick={()=>run('approve')}>✓ ใช้รูปนี้กับงานนี้</button><button className="button" disabled={editorSaving} onClick={()=>run('reject')}>✕ ไม่ตรงงานนี้</button></div></div><div className="ai-editor-options"><label>ถ้ารูปนี้เป็นงานอื่น ให้แก้ Mapping หลัก<select value={editorTask} disabled={editorSaving} onChange={e=>setEditorTask(e.target.value)}>{editor.tasks.map(t=><option key={t.id} value={t.id}>{t.source_task_no||'-'}. {t.task_name}{t.area?` — ${t.area}`:''}</option>)}</select></label><label>หมายเหตุ<input value={editorNote} disabled={editorSaving} onChange={e=>setEditorNote(e.target.value)} placeholder="เช่น รูปนี้เป็นงานฝ้าชั้น 2 ไม่ใช่งานสี"/></label><button className="button" disabled={editorSaving||!editorTask} onClick={()=>run('remap')}>บันทึก Mapping หลักใหม่</button><div className="ai-alt-head"><b>เลือกรูปอื่นแทนได้ทันที</b><span>AI + พฤติกรรมที่ Golf เคยเลือก</span></div><div className="ai-alt-grid">{editor.alternatives.map(a=><button key={a.id} disabled={editorSaving} onClick={()=>run('approve',a.id)}><img src={`/api/drive-photo?fileId=${encodeURIComponent(a.drive_file_id)}&size=480`} alt={a.file_name}/><span>{a.ai?`AI ${Math.round(Number(a.ai.score))}%`:'Fallback'}{a.learning?` • เรียนรู้ ${a.learning>0?'+':''}${a.learning}`:''} • {dateLabel(a.photo_date)}</span><small>{a.ai?.detected_work||a.sourceTask?.task_name||a.file_name}</small><em>ใช้รูปนี้แทน</em></button>)}</div>{!editor.alternatives.length&&<div className="notice">ยังไม่มีรูปทางเลือกใน Candidate ชุดนี้</div>}{editorMessage&&<div className="notice" style={{color:'var(--red)'}}>{editorMessage}</div>}</div></div></section></div>,document.fullscreenElement||document.body):null

  return <>{toast&&<div className="ai-feedback-toast">{toast}</div>}{modal}<style jsx global>{`
    .ai-visual-status{margin:0 0 8px;padding:7px 10px;border-radius:9px;background:#edf5ff;border:1px solid #cbdff7;color:#35597d;font-size:10px;font-weight:800}.ai-photo-actionbar{display:flex;gap:6px;align-items:center;justify-content:flex-end;padding:7px 8px;border-top:1px solid #e8e1d7;background:#f8f6f1}.ai-photo-actionbar button{border:1px solid #d4d9df;background:#fff;color:#33475e;border-radius:8px;padding:6px 9px;font-size:9px;font-weight:850;cursor:pointer;min-height:28px}.ai-photo-actionbar button:hover{border-color:#5d87ae;background:#edf5ff}.ai-photo-actionbar button.active{background:#e8f6ee;border-color:#83bf9e;color:#17643f}.ai-photo-actionbar button.active-reject{background:#fff0ee;border-color:#dfa59f;color:#963b35}.ai-photo-actionbar button:disabled{opacity:.5;cursor:wait}.ai-feedback-toast{position:fixed;z-index:2147483647;right:18px;bottom:18px;max-width:min(430px,calc(100vw - 36px));padding:11px 14px;border-radius:10px;background:#17334f;color:white;font-size:11px;font-weight:800;box-shadow:0 10px 30px rgba(0,0,0,.24)}
    .ai-editor-backdrop{position:fixed;inset:0;z-index:2147483646;background:rgba(5,14,27,.76);display:grid;place-items:center;padding:18px;backdrop-filter:blur(5px)}.ai-editor-modal{width:min(1180px,96vw);max-height:94vh;overflow:auto;background:#fffdf9;border-radius:18px;box-shadow:0 28px 80px rgba(0,0,0,.34);border:1px solid #ddd5c7}.ai-editor-modal>header{position:sticky;top:0;z-index:2;background:#fffdf9;display:flex;justify-content:space-between;gap:12px;padding:16px 18px;border-bottom:1px solid #e4ded4}.ai-editor-modal header span{font-size:9px;font-weight:900;letter-spacing:1.2px;color:#a97920}.ai-editor-modal h3{margin:3px 0;font-size:21px;color:#17243a}.ai-editor-modal header p{margin:0;font-size:11px;color:#6f7781}.ai-editor-body{display:grid;grid-template-columns:minmax(300px,.8fr) minmax(0,1.2fr);gap:16px;padding:16px}.ai-editor-current img{width:100%;height:370px;object-fit:contain;background:#111923;border-radius:12px}.ai-editor-ai{display:grid;gap:3px;padding:10px 0}.ai-editor-ai b{font-size:15px;color:#244d78}.ai-editor-ai span{font-size:11px;color:#374a61}.ai-editor-ai small{font-size:10px;color:#6f7781;line-height:1.4}.ai-editor-buttons{display:flex;gap:7px;flex-wrap:wrap}.ai-editor-options{display:grid;align-content:start;gap:10px}.ai-editor-options label{display:grid;gap:5px;font-size:11px;font-weight:850;color:#566273}.ai-editor-options select,.ai-editor-options input{width:100%;padding:10px;border:1px solid #ddd5c7;border-radius:9px;background:white}.ai-alt-head{display:flex;justify-content:space-between;align-items:end;margin-top:4px}.ai-alt-head b{font-size:13px}.ai-alt-head span{font-size:9px;color:#7a8490}.ai-alt-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.ai-alt-grid>button{padding:0;text-align:left;border:1px solid #dfd8cc;border-radius:11px;overflow:hidden;background:#fff;cursor:pointer;display:grid}.ai-alt-grid>button:hover{border-color:#5b8fc3;box-shadow:0 5px 16px rgba(35,83,128,.12)}.ai-alt-grid img{width:100%;height:130px;object-fit:cover;background:#edf0f2}.ai-alt-grid span,.ai-alt-grid small,.ai-alt-grid em{padding:0 8px}.ai-alt-grid span{font-size:10px;font-weight:850;color:#315f9e;margin-top:7px}.ai-alt-grid small{font-size:9px;color:#6d7784;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ai-alt-grid em{font-size:9px;font-style:normal;font-weight:850;color:#247951;margin:5px 0 8px}@media(max-width:820px){.ai-editor-body{grid-template-columns:1fr}.ai-editor-current img{height:300px}}@media(max-width:560px){.ai-photo-actionbar{justify-content:stretch}.ai-photo-actionbar button{flex:1}.ai-alt-grid{grid-template-columns:1fr}.ai-editor-backdrop{padding:6px}.ai-editor-modal{width:100%;max-height:97vh}.ai-editor-modal h3{font-size:17px}}@media print{.ai-photo-actionbar,.ai-visual-status,.ai-editor-backdrop,.ai-feedback-toast{display:none!important}}
  `}</style></>
}
