'use client'
import {useEffect,useState} from 'react'
import {getSupabase} from '@/lib/supabase'
import useAccessRole from '@/components/useAccessRole'
import {canEditProcurement} from '@/lib/accessControl'
import {getActivitySessionId} from '@/lib/activityLog'
type Row={id:string;vendor:string|null;item_name:string|null;current_status:string|null;expected_delivery_text:string|null;expected_delivery:string|null;condition_note:string|null}
export default function ProcurementEditPanel(){const {role}=useAccessRole();const editable=canEditProcurement(role);const [rows,setRows]=useState<Row[]>([]);const [id,setId]=useState('');const [f,setF]=useState({current_status:'',expected_delivery_text:'',expected_delivery:'',condition_note:'',review_status:'pending'});const [msg,setMsg]=useState('');
 useEffect(()=>{if(!editable)return;getSupabase().from('v_procurement_source_rows').select('id,vendor,item_name,current_status,expected_delivery_text,expected_delivery,condition_note').order('source_updated_at',{ascending:false}).limit(500).then(({data})=>setRows((data||[]) as Row[]))},[editable])
 const choose=(v:string)=>{setId(v);const r=rows.find(x=>x.id===v);if(r)setF({current_status:r.current_status||'',expected_delivery_text:r.expected_delivery_text||'',expected_delivery:r.expected_delivery||'',condition_note:r.condition_note||'',review_status:'pending'})}
 const save=async()=>{if(!id)return;const {error}=await getSupabase().rpc('procurement_save_web_override',{p_item_id:id,p_current_status:f.current_status||null,p_expected_delivery_text:f.expected_delivery_text||null,p_expected_delivery:f.expected_delivery||null,p_condition_note:f.condition_note||null,p_review_status:f.review_status,p_client_session_id:getActivitySessionId(),p_user_agent:navigator.userAgent});setMsg(error?error.message:'บันทึกสถานะจัดซื้อเรียบร้อย')}
 if(!editable)return null;return <section className="panel procurement-editor"><b>แก้ไข / ยืนยันการจัดซื้อ-จัดจ้าง</b><div className="grid"><label>รายการ<select value={id} onChange={e=>choose(e.target.value)}><option value="">เลือกรายการ</option>{rows.map(r=><option key={r.id} value={r.id}>{(r.vendor?r.vendor+' — ':'')+(r.item_name||'-')}</option>)}</select></label><label>สถานะ<input value={f.current_status} onChange={e=>setF({...f,current_status:e.target.value})}/></label><label>กำหนดส่ง<input value={f.expected_delivery_text} onChange={e=>setF({...f,expected_delivery_text:e.target.value})}/></label><label>วันที่<input type="date" value={f.expected_delivery} onChange={e=>setF({...f,expected_delivery:e.target.value})}/></label><label className="wide">เงื่อนไข / หมายเหตุ<textarea value={f.condition_note} onChange={e=>setF({...f,condition_note:e.target.value})}/></label><label>การยืนยัน<select value={f.review_status} onChange={e=>setF({...f,review_status:e.target.value})}><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="needs_review">Needs review</option></select></label></div><button className="button primary" disabled={!id} onClick={save}>บันทึก / ยืนยัน</button>{msg&&<span className="small" style={{marginLeft:8}}>{msg}</span>}<style jsx>{`.procurement-editor{margin-bottom:12px;padding:12px}.grid{display:grid;grid-template-columns:2fr 1fr 1fr 150px;gap:8px;margin:10px 0}.grid label{display:grid;gap:4px;font-size:10px;font-weight:800;color:var(--muted)}.grid input,.grid select,.grid textarea{border:1px solid var(--line);border-radius:8px;padding:8px;font:inherit;background:#fff}.wide{grid-column:span 3}.grid textarea{min-height:60px}@media(max-width:760px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}}`}</style></section>
}