'use client'
import {useEffect,useState} from 'react'
import {getSupabase} from '@/lib/supabase'
import useAccessRole from '@/components/useAccessRole'
import {canEditSchedule} from '@/lib/accessControl'
import {getActivitySessionId} from '@/lib/activityLog'
type Row={id:string;source_task_no:string|null;task_name:string;site_status:string|null;next_action:string|null;target_close:string|null;blocker:string|null;notes:string|null;web_review_status:string|null}
export default function ScheduleEditPanel(){
 const {role}=useAccessRole();const editable=canEditSchedule(role);const [rows,setRows]=useState<Row[]>([]);const [id,setId]=useState('');const [form,setForm]=useState({site_status:'',next_action:'',target_close:'',blocker:'',notes:'',review_status:'pending'});const [msg,setMsg]=useState('')
 useEffect(()=>{if(!editable)return;getSupabase().from('v_schedule_tasks').select('id,source_task_no,task_name,site_status,next_action,target_close,blocker,notes,web_review_status').neq('source_task_no','1').order('source_task_no').then(({data})=>setRows((data||[]) as Row[]))},[editable])
 const choose=(v:string)=>{setId(v);const r=rows.find(x=>x.id===v);if(r)setForm({site_status:r.site_status||'',next_action:r.next_action||'',target_close:r.target_close||'',blocker:r.blocker||'',notes:r.notes||'',review_status:r.web_review_status||'pending'})}
 const save=async()=>{if(!id)return;setMsg('');const {error}=await getSupabase().rpc('schedule_save_web_override',{p_task_id:id,p_site_status:form.site_status||null,p_next_action:form.next_action||null,p_target_close:form.target_close||null,p_blocker:form.blocker||null,p_notes:form.notes||null,p_review_status:form.review_status,p_client_session_id:getActivitySessionId(),p_user_agent:navigator.userAgent});setMsg(error?error.message:'บันทึกแผนงานเรียบร้อย')}
 if(!editable)return null
 return <section className="panel editor-box"><b>แก้ไข / ยืนยันแผนงาน</b><div className="editor-grid"><label>รายการ<select value={id} onChange={e=>choose(e.target.value)}><option value="">เลือกรายการ</option>{rows.map(r=><option key={r.id} value={r.id}>{(r.source_task_no?r.source_task_no+'. ':'')+r.task_name}</option>)}</select></label><label>สถานะ<input value={form.site_status} onChange={e=>setForm({...form,site_status:e.target.value})}/></label><label>Target Close<input type="date" value={form.target_close} onChange={e=>setForm({...form,target_close:e.target.value})}/></label><label>การยืนยัน<select value={form.review_status} onChange={e=>setForm({...form,review_status:e.target.value})}><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="needs_review">Needs review</option></select></label><label className="wide">งานถัดไป<textarea value={form.next_action} onChange={e=>setForm({...form,next_action:e.target.value})}/></label><label className="wide">Blocker / หมายเหตุ<textarea value={form.blocker+'\n'+form.notes} onChange={e=>{const [a,...b]=e.target.value.split('\n');setForm({...form,blocker:a,notes:b.join('\n')})}}/></label></div><button className="button primary" type="button" disabled={!id} onClick={save}>บันทึก / ยืนยัน</button>{msg&&<span className="small" style={{marginLeft:8}}>{msg}</span>}<style jsx>{`.editor-box{margin-bottom:12px;padding:12px}.editor-grid{display:grid;grid-template-columns:2fr 1fr 150px 150px;gap:8px;margin:10px 0}.editor-grid label{display:grid;gap:4px;font-size:10px;font-weight:800;color:var(--muted)}.editor-grid input,.editor-grid select,.editor-grid textarea{border:1px solid var(--line);border-radius:8px;padding:8px;font:inherit;background:#fff}.editor-grid textarea{min-height:62px;resize:vertical}.editor-grid .wide{grid-column:span 2}@media(max-width:760px){.editor-grid{grid-template-columns:1fr}.editor-grid .wide{grid-column:auto}}`}</style></section>
}