drop policy if exists photo_task_feedback_write_manager_engineer on public.photo_task_feedback;
create policy photo_task_feedback_insert_manager_engineer on public.photo_task_feedback for insert to authenticated with check (exists (select 1 from public.profiles p where p.user_id=(select auth.uid()) and p.active=true and p.role in ('manager','engineer')));
create policy photo_task_feedback_update_manager_engineer on public.photo_task_feedback for update to authenticated using (exists (select 1 from public.profiles p where p.user_id=(select auth.uid()) and p.active=true and p.role in ('manager','engineer'))) with check (exists (select 1 from public.profiles p where p.user_id=(select auth.uid()) and p.active=true and p.role in ('manager','engineer')));
create policy photo_task_feedback_delete_manager_engineer on public.photo_task_feedback for delete to authenticated using (exists (select 1 from public.profiles p where p.user_id=(select auth.uid()) and p.active=true and p.role in ('manager','engineer')));
create index if not exists photo_task_feedback_reviewed_by_idx on public.photo_task_feedback(reviewed_by) where reviewed_by is not null;

drop policy if exists photo_ai_task_scores_write_manager_engineer on public.photo_ai_task_scores;
create policy photo_ai_task_scores_insert_manager_engineer on public.photo_ai_task_scores for insert to authenticated with check (exists (select 1 from public.profiles p where p.user_id=(select auth.uid()) and p.active=true and p.role in ('manager','engineer')));
create policy photo_ai_task_scores_update_manager_engineer on public.photo_ai_task_scores for update to authenticated using (exists (select 1 from public.profiles p where p.user_id=(select auth.uid()) and p.active=true and p.role in ('manager','engineer'))) with check (exists (select 1 from public.profiles p where p.user_id=(select auth.uid()) and p.active=true and p.role in ('manager','engineer')));
create policy photo_ai_task_scores_delete_manager_engineer on public.photo_ai_task_scores for delete to authenticated using (exists (select 1 from public.profiles p where p.user_id=(select auth.uid()) and p.active=true and p.role in ('manager','engineer')));